apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.sno.sno1.ad.brycech.com
  path: "/todo"
  to:
    kind: Service
    name: frontend-emea
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
